connections {
   rw {
      local_addrs  = 172.22.0.41
      local {
         id = %any
         auth = eap-aka
      }
      remote {
         auth = eap-aka
      }
      children {
         net {
            local_ts = 0.0.0.0/0
            mark_in = 2
            mark_out = 4
            esp_proposals = default
         }
      }
      version = 2
      proposals = aes256-sha256-prfsha256-modp2048,aes256-sha1-prfsha1-modp2048,aes256-sha512-prfsha512-modp2048,aes256-sha256-prfsha256-modp3072,aes256-sha256-prfsha256-ecp256,aes128-sha256-prfsha256-modp2048,aes128-sha1-prfsha1-modp2048,aes128-aesxcbc-prfaesxcbc-modp2048,aes128-sha256-prfsha256-modp1536,aes128-sha1-prfsha1-modp1536,aes256-sha256-prfsha256-modp1536,aes256-sha1-prfsha1-modp1536,aes128-sha256-prfsha256-modp1024,aes128-sha1-prfsha1-modp1024,aes128-aesxcbc-prfaesxcbc-modp1024,aes256-sha256-prfsha256-modp1024,aes256-sha1-prfsha1-modp1024,aes256-aesxcbc-prfaesxcbc-modp1024,aes128-sha256-modp3072,aes128-sha1-modp1024,default
      vips = 0.0.0.0, ::
   }
}
pools {
}
secrets {
}
attr {
   pcscf = 172.22.0.21
}
